name: Python CI

on:
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install poetry
        run: pipx install poetry==1.2.2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry
        
      - name: Install Dependencies
        run: poetry install --no-root
      
      - name: Lint
        run: make lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install poetry
        run: pipx install poetry==1.2.2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry
        
      - name: Install Dependencies
        run: poetry install --no-root
      
      - name: Test
        run: make test
  
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install poetry
        run: pipx install poetry==1.2.2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry
        
      - name: Install Dependencies
        run: poetry install --no-root
      
      - name: Get Test Coverage
        run: make test-cov
      
      - name: Commit Test Coverage
        uses: MichsKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          report-only-changed-files: true